=== SebakPetra/FB8YPQ_XmlGyak/XMLTaskFB8YPQ/DOMParseFB8YPQ/galaXMLSchemaFB8YPQ.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="galaSzervezes">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="Fellepes" type="fellepesType"/>
                    <xs:element name="Szervezo" type="szervezoType"/>
                    <xs:element name="Tancgala" type="tancgalaType"/>
                    <xs:element name="Tanciskola" type="tanciskolaType"/>
                    <xs:element name="Csoport" type="csoportType"/>
                    <xs:element name="Tancora" type="tancoraType"/>
                    <xs:element name="Koreografia" type="koreografiaType"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="koreoId_PK">
            <xs:selector xpath="Koreografia"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="csoportId_PK">
            <xs:selector xpath="Csoport"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="szervezoId_PK">
            <xs:selector xpath="Szervezo"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="tanciskolaId_PK">
            <xs:selector xpath="Tanciskola"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="tancgalaId_PK">
            <xs:selector xpath="Tancgala"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="koreoId_FK" refer="koreoId_PK">
            <xs:selector xpath="Fellepes"/>
            <xs:field xpath="@koreoId"/>
        </xs:keyref>
        <xs:keyref name="csoportId_FK" refer="csoportId_PK">
            <xs:selector xpath="Fellepes"/>
            <xs:field xpath="@csoportId"/>
        </xs:keyref>
        <xs:keyref name="tanciskolaId_FK" refer="tanciskolaId_PK">
            <xs:selector xpath="Csoport"/>
            <xs:field xpath="@tanciskolaId"/>
        </xs:keyref>
        <xs:keyref name="tancgalaId_FK" refer="tancgalaId_PK">
            <xs:selector xpath="Tanciskola"/>
            <xs:field xpath="@tancgalaId"/>
        </xs:keyref>
        <xs:keyref name="szervezoId_FK" refer="szervezoId_PK">
            <xs:selector xpath="Tancgala"/>
            <xs:field xpath="@szervezoId"/>
        </xs:keyref>
    </xs:element>

    <xs:complexType name="fellepesType">
        <xs:sequence>
            <xs:element name="szinpad"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="koreoId" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="csoportId" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="szervezoType">
        <xs:sequence>
            <xs:element name="Ceg" type="xs:string"/>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Telefonszam" type="telType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="tancgalaType">
        <xs:sequence>
            <xs:element name="Helyszin" type="xs:string"/>
            <xs:element name="Idopont" type="tancgalaIdopontType"/>
            <xs:element name="Idotartam" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="szervezoId" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="tanciskolaType">
        <xs:sequence>
            <xs:element name="TanciskolaNev" type="xs:string"/>
            <xs:element name="Telefonszam" type="telType"/>
            <xs:element name="Vezeto" type="vezetoType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="tancgalaId" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="csoportType">
        <xs:sequence>
            <xs:element name="Korosztaly" type="xs:string"/>
            <xs:element name="Letszam" type="xs:integer"/>
            <xs:element name="Csoportnev" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="tanciskolaId" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="tancoraType">
        <xs:sequence>
            <xs:element name="Idopont" type="tancoraIdopontType"/>
            <xs:element name="Terem" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="csoportId" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="koreografiaType">
        <xs:sequence>
            <xs:element name="Zene" type="xs:string"/>
            <xs:element name="Stilus" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    <xs:complexType name="vezetoType">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Tapasztalat" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="tancoraIdopontType">
        <xs:restriction base="xs:string">
          <xs:pattern value="Hétfő [0-9][0-9]*|Kedd [0-9][0-9]*|Szerda [0-9][0-9]*|Csütörtök [0-9][0-9]*|Péntek [0-9][0-9]*"/>
        </xs:restriction>
      </xs:simpleType>

      <xs:simpleType name="tancgalaIdopontType">
        <xs:restriction base="xs:string">
          <xs:pattern value="[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]. [0-9][0-9]*:[0-9][0-9]"/>
        </xs:restriction>
      </xs:simpleType>

	<xs:simpleType name="telType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}-\d{3}-\d{2}-\d{2}"/>
            <xs:pattern value="\d{2}-\d{3}-\d{3}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== SebakPetra/FB8YPQ_XmlGyak/XMLTaskFB8YPQ/DOMParseFB8YPQ/XMLFB8YPQ.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><galaSzervezes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="galaXMLSchemaFB8YPQ.xsd">
    <Fellepes csoportId="1" id="1" koreoId="1">
        <szinpad>Kicsi</szinpad>
    </Fellepes>
    <Fellepes csoportId="4" id="2" koreoId="2">
        <szinpad>Nagy</szinpad>
    </Fellepes>
    <Fellepes csoportId="3" id="3" koreoId="2">
        <szinpad>Nagy</szinpad>
    </Fellepes>
    <Fellepes csoportId="3" id="4" koreoId="3">
        <szinpad>Kicsi</szinpad>
    </Fellepes>
    <Fellepes csoportId="2" id="5" koreoId="3">
        <szinpad>Kicsi</szinpad>
    </Fellepes>
    <Szervezo id="1">
        <Ceg>DanceHall Kft.</Ceg>
        <Nev>Nagy Fanni</Nev>
        <Telefonszam>12-345-32-23</Telefonszam>
    </Szervezo>
    <Tancgala id="1" szervezoId="1">
        <Helyszin>Miskolc</Helyszin>
        <Idopont>2021.01.30. 15:00</Idopont>
        <Idotartam>2 óra</Idotartam>
    </Tancgala>
    <Tancgala id="2" szervezoId="1">
        <Helyszin>Debrecen</Helyszin>
        <Idopont>2022.04.12. 19:00</Idopont>
        <Idotartam>1 óra</Idotartam>
    </Tancgala>
    <Tanciskola id="1" tancgalaId="1">
        <TanciskolaNev>Elte</TanciskolaNev>
        <Telefonszam>21-377-20-69</Telefonszam>
        <Vezeto>
            <Nev>Tóth Evelin</Nev>
            <Tapasztalat>3 év</Tapasztalat>
        </Vezeto>
    </Tanciskola>
    <Tanciskola id="2" tancgalaId="2">
        <TanciskolaNev>Dance Elit</TanciskolaNev>
        <Telefonszam>21-343-22-88</Telefonszam>
        <Vezeto>
            <Nev>Hajdú Sándor</Nev>
            <Tapasztalat>1 év</Tapasztalat>
        </Vezeto>
    </Tanciskola>
    <Csoport id="1" tanciskolaId="1">
        <Korosztaly>9-11</Korosztaly>
        <Letszam>10</Letszam>
        <Csoportnev>CoolKids</Csoportnev>
    </Csoport>
    <Csoport id="2" tanciskolaId="1">
        <Korosztaly>12-14</Korosztaly>
        <Letszam>13</Letszam>
        <Csoportnev>Girls</Csoportnev>
    </Csoport>
    <Csoport id="3" tanciskolaId="1">
        <Korosztaly>15-17</Korosztaly>
        <Letszam>9</Letszam>
        <Csoportnev>Contemp</Csoportnev>
    </Csoport>
    <Csoport id="4" tanciskolaId="2">
        <Korosztaly>8-11</Korosztaly>
        <Letszam>19</Letszam>
        <Csoportnev>Unicorns</Csoportnev>
    </Csoport>
    <Csoport id="5" tanciskolaId="2">
        <Korosztaly>12-17</Korosztaly>
        <Letszam>6</Letszam>
        <Csoportnev>TroubleMakers</Csoportnev>
    </Csoport>
    <Tancora csoportId="1" id="1">
        <Idopont>Hétfő 14</Idopont>
        <Terem>3</Terem>
    </Tancora>
    <Tancora csoportId="2" id="2">
        <Idopont>Hétfő 16</Idopont>
        <Terem>3</Terem>
    </Tancora>
    <Tancora csoportId="3" id="3">
        <Idopont>Kedd 14</Idopont>
        <Terem>3</Terem>
    </Tancora>
    <Tancora csoportId="4" id="4">
        <Idopont>Szerda 14</Idopont>
        <Terem>3</Terem>
    </Tancora>
    <Tancora csoportId="4" id="5">
        <Idopont>Péntek 18</Idopont>
        <Terem>3</Terem>
    </Tancora>
    <Koreografia id="1">
        <Zene>Adele-Rolling in the deep</Zene>
        <Stilus>HipHop</Stilus>
    </Koreografia>
    <Koreografia id="2">
        <Zene>Betti-Cry for help</Zene>
        <Stilus>Modern</Stilus>
    </Koreografia>
    <Koreografia id="3">
        <Zene>Jatleg-Égen át</Zene>
        <Stilus>HipHop</Stilus>
    </Koreografia>
</galaSzervezes>
